version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: monday
    groups:
      patches:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: 
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/docker/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
