sequenceDiagram
  actor U as User
  participant A as Application
  participant E as Entitlement Service
  participant S as Storage

  U->>A: Makes API Request
  A->>A: Obtains security plugin
  note over A: Uses SecurityPluginLoader.load()
  A->>A: Obtains user identity
  note over A: Uses IdentityProvider API
  A->>E: Requests users attributes
  note over A,E: Uses AttributesProvider API<br /><br />Application treats User Attributes as <br />opaque data structures
  A->>A: Prepares an authorizer
  note over A: Gets an instance of the Authorizer for this request
  A->>A: Verifies request is permitted
  note over A: Call Authorizer.canUse()
  alt Request Permitted
    loop Until API request satisfied
      A->>S: Queries underlying storage
      S->>A: Returns stored data
      loop Each data item
        A->>A: Parses label byte sequences
        note over A: Uses SecurityLabelsParser API<br /><br />Application treats labels as <br />opaque data structures
        A->>A: Uses configured Security Plugin to make access decisions
        note over A: Calls Authorizer.canRead()/canWrite() as appropriate
      end
    end
    A->>U: Returns security filtered response
    note over A,U: E.g. send HTTP 200 response
  else
    A->>U: Rejects request
    note over A,U: E.g. send HTTP 403 response
  end